# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#publishing-using-gradle

name: Release

on:
  workflow_dispatch

jobs:
  jpackage:
    runs-on: ubuntu-24.04-arm

    steps:
      - uses: actions/checkout@v3
      - name: Set Up Java18
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '18'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Build
        run: |
          ./gradlew app:releaseJarZip
          ls app/build/distributions/
          ls app/build/jpackage/

      - name: Release-ubuntu
        uses: softprops/action-gh-release@v1
        with:
          files: |
            app/build/jpackage/*.rpm
            app/build/jpackage/*.deb
            app/build/jpackage/*.zip
          draft: true
          fail_on_unmatched_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
